/**
 * GraphQL Queries - Re-export all queries
 */

// Fragments
export * from './fragments';

// Project Queries
export {
  GET_ALL_PROJECTS,
  GET_PROJECT_BY_SLUG,
  GET_FEATURED_PROJECTS,
  GET_ALL_PROJECT_SLUGS,
  GET_PROJECTS_BY_TYPE,
  GET_PROJECTS_BY_TECH_STACK,
  GET_PROJECT_WITH_RELATED,
  GET_PROJECT_COUNT,
  GET_ALL_PROJECT_TYPES,
  GET_ALL_TECH_STACKS,
} from './projects';

// Post Queries
export {
  GET_ALL_POSTS,
  GET_POST_BY_SLUG,
  GET_RECENT_POSTS,
  GET_ALL_POST_SLUGS,
  GET_POSTS_BY_CATEGORY,
  GET_POSTS_BY_TAG,
  GET_POSTS_BY_AUTHOR,
  GET_POSTS_COUNT,
  GET_ALL_CATEGORIES,
  GET_ALL_TAGS,
  GET_RELATED_POSTS,
  SEARCH_POSTS,
} from './posts';

// Site Settings Queries
export {
  GET_SITE_SETTINGS,
  GET_GENERAL_SETTINGS,
  GET_READING_SETTINGS,
  GET_PRIMARY_MENU,
  GET_FOOTER_MENU,
  GET_MENU_BY_LOCATION,
  GET_ALL_MENUS,
  GET_SITE_INFO,
  GET_HEADER_SETTINGS,
  GET_FOOTER_SETTINGS,
} from './site-settings';
